"""Conservative output limits for MCP tool responses."""

from __future__ import annotations

DEFAULT_LIST_SESSIONS = 50
MAX_LIST_SESSIONS = 200

DEFAULT_ANALYZE_OBSERVED = 100
MAX_ANALYZE_OBSERVED = 500

DEFAULT_DECODE_LIMIT = 100
MAX_DECODE_LIMIT = 500

DEFAULT_TP_COMPLETED = 50
MAX_TP_COMPLETED = 200

DEFAULT_DBC_PREVIEW_LINES = 100
MAX_DBC_PREVIEW_LINES = 500

DEFAULT_LIST_ASSETS = 100
MAX_LIST_ASSETS = 200

DEFAULT_OBSERVE_DURATION_S = 3.0
MAX_OBSERVE_DURATION_S = 15.0

DEFAULT_TRAFFIC_ROWS = 50
MAX_TRAFFIC_ROWS = 200

DEFAULT_COMPARE_WINDOW_S = 3.0
MAX_COMPARE_WINDOW_S = 30.0
