"""Conservative output limits for MCP tool responses."""

from __future__ import annotations

DEFAULT_LIST_SESSIONS = 50
MAX_LIST_SESSIONS = 200

DEFAULT_ANALYZE_OBSERVED = 100
MAX_ANALYZE_OBSERVED = 500

DEFAULT_DECODE_LIMIT = 100
MAX_DECODE_LIMIT = 500

DEFAULT_TP_COMPLETED = 50
MAX_TP_COMPLETED = 200

DEFAULT_DBC_PREVIEW_LINES = 100
MAX_DBC_PREVIEW_LINES = 500

DEFAULT_LIST_ASSETS = 100
MAX_LIST_ASSETS = 200

DEFAULT_OBSERVE_DURATION_S = 3.0
MAX_OBSERVE_DURATION_S = 15.0

DEFAULT_TRAFFIC_ROWS = 50
MAX_TRAFFIC_ROWS = 200

DEFAULT_COMPARE_WINDOW_S = 3.0
MAX_COMPARE_WINDOW_S = 30.0

DEFAULT_SIGNAL_CANDIDATES = 20
MAX_SIGNAL_CANDIDATES = 100

DEFAULT_FIELD_CANDIDATES = 50
MAX_FIELD_CANDIDATES = 200

MAX_COUNTER_CANDIDATES = 32
MAX_CHECKSUM_CANDIDATES = 32
MAX_REPEATED_PAIRS = 20
MAX_REFERENCE_SAMPLES = 10_000

DEFAULT_LIST_RESEARCH_CANDIDATES = 50
MAX_LIST_RESEARCH_CANDIDATES = 200

DEFAULT_LIST_SESSION_EVENTS = 50
MAX_LIST_SESSION_EVENTS = 200

DEFAULT_CANDIDATE_VALUE_PREVIEW = 50
MAX_CANDIDATE_VALUE_PREVIEW = 200

DEFAULT_DBC_INSPECT_MESSAGES = 50
MAX_DBC_INSPECT_MESSAGES = 200
DEFAULT_DBC_INSPECT_SIGNALS = 32
MAX_DBC_INSPECT_SIGNALS = 64
DEFAULT_DBC_COVERAGE_ROWS = 100
MAX_DBC_COVERAGE_ROWS = 500
MAX_LIST_DBC_SOURCES = 100

DEFAULT_LIST_REFERENCE_SOURCES = 50
MAX_LIST_REFERENCE_SOURCES = 100
DEFAULT_REFERENCE_SEARCH_LIMIT = 25
MAX_REFERENCE_SEARCH_LIMIT = 100


def clamp_limit(value: int | None, default: int, maximum: int) -> int:
    if value is None:
        return default
    if value <= 0:
        return default
    return min(value, maximum)
