"""Generate asset-specific research DBC from confirmed candidates."""

from __future__ import annotations

from collections import Counter, defaultdict
from dataclasses import dataclass, field
from pathlib import Path

from canresearch import __version__
from canresearch.core.assets import default_dbc_filename, get_asset_by_key
from canresearch.core.dbc_generation import GenerationWarning
from canresearch.core.dbc_identifiers import sanitize_dbc_identifier
from canresearch.core.dbc_model import DbcDatabase, DbcMessage, DbcProvenance, DbcSignal
from canresearch.core.dbc_position import encode_dbc_extended_id, signal_bit_range
from canresearch.core.dbc_writer import render_dbc, write_dbc
from canresearch.core.j1939 import parse_j1939_id
from canresearch.core.research_candidates import (
    CandidateClassification,
    ResearchCandidateRecord,
    list_all_confirmed_research_candidates,
)
from canresearch.storage.database import default_db_path, initialize

DEFAULT_DLC = 8
DEFAULT_NODE = "Vector__XXX"
DBC_TYPE_RESEARCH = "research"

DBC_EXCLUDED_CLASSIFICATIONS = frozenset(
    {
        CandidateClassification.COUNTER.value,
        CandidateClassification.CHECKSUM.value,
        CandidateClassification.RESERVED.value,
    }
)


@dataclass(frozen=True, slots=True)
class ResearchDbcSummary:
    asset_key: str
    asset_id: str
    dbc_type: str
    confirmed_signal_count: int
    messages_generated: int
    signals_generated: int
    signals_skipped: int
    warnings: tuple[GenerationWarning, ...] = field(default_factory=tuple)
    database: DbcDatabase = field(default_factory=lambda: DbcDatabase(version="", nodes=()))
    output_path: Path | None = None

    @property
    def warning_counts(self) -> dict[str, int]:
        return dict(Counter(w.category for w in self.warnings))


def _bit_ranges_overlap(a: tuple[int, int], b: tuple[int, int]) -> bool:
    return a[0] < b[1] and b[0] < a[1]


def _frame_group_key(candidate: ResearchCandidateRecord) -> tuple[bool, int]:
    return candidate.is_extended, candidate.can_id


def _research_message_name_fallback(candidate: ResearchCandidateRecord) -> str:
    if candidate.is_extended:
        return sanitize_dbc_identifier(f"Research_{candidate.can_id:08X}")
    return sanitize_dbc_identifier(f"Research_{candidate.can_id:03X}_11b")


def _research_message_name(
    candidate: ResearchCandidateRecord,
    *,
    used_names: set[str],
) -> str:
    if candidate.is_extended and candidate.can_id <= 0x1FFFFFFF:
        try:
            parsed = parse_j1939_id(candidate.can_id)
            sa = (
                candidate.source_address
                if candidate.source_address is not None
                else parsed.source_address
            )
            if parsed.is_pdu1:
                da = (
                    candidate.destination_address
                    if candidate.destination_address is not None
                    else parsed.destination_address
                )
                if da is not None:
                    raw = f"Prop_PGN{parsed.pgn}_SA{sa:02X}_DA{da:02X}"
                else:
                    raw = f"Prop_PGN{parsed.pgn}_SA{sa:02X}"
            else:
                raw = f"Prop_PGN{parsed.pgn}_SA{sa:02X}"
            base = sanitize_dbc_identifier(raw)
            if base not in used_names:
                return base
        except ValueError:
            pass
    fallback = _research_message_name_fallback(candidate)
    if fallback not in used_names:
        return fallback
    disambiguated = sanitize_dbc_identifier(
        f"{fallback}_ID{candidate.can_id:08X}"
        if candidate.is_extended
        else f"{fallback}_ID{candidate.can_id:03X}"
    )
    return disambiguated


def _load_confirmed_candidates(
    asset_key: str,
    *,
    db_path: Path,
    include_protocol_fields: bool,
) -> tuple[list[ResearchCandidateRecord], int]:
    all_confirmed = list_all_confirmed_research_candidates(asset_key, db_path=db_path)
    selected: list[ResearchCandidateRecord] = []
    skipped = 0
    for candidate in all_confirmed:
        if (
            not include_protocol_fields
            and candidate.classification in DBC_EXCLUDED_CLASSIFICATIONS
        ):
            skipped += 1
            continue
        if not candidate.signal_name:
            skipped += 1
            continue
        if candidate.factor is None or candidate.offset is None:
            skipped += 1
            continue
        selected.append(candidate)
    return selected, skipped


def _session_ids_for_candidates(candidates: list[ResearchCandidateRecord]) -> tuple[str, ...]:
    sessions = {c.origin_session_id for c in candidates if c.origin_session_id}
    return tuple(sorted(sessions))


def _provenance_comments(
    *,
    asset_key: str,
    confirmed_count: int,
    session_ids: tuple[str, ...],
) -> tuple[str, ...]:
    session_text = ", ".join(session_ids) if session_ids else "none"
    return (
        "Generated by CAN Research",
        f"Asset: {asset_key}",
        f"DBC type: {DBC_TYPE_RESEARCH}",
        f"Confirmed research signals: {confirmed_count}",
        f"Source sessions: {session_text}",
        f"Generator: can-research {__version__}",
    )


def _signal_comment(candidate: ResearchCandidateRecord) -> str:
    session = candidate.origin_session_id or "unknown"
    return (
        f"Candidate ID: {candidate.id}; "
        f"Origin session: {session}; "
        f"Classification: {candidate.classification}"
    )


def generate_asset_research_dbc(
    asset_key: str,
    *,
    db_path: Path | None = None,
    include_protocol_fields: bool = False,
) -> ResearchDbcSummary:
    """Build an in-memory research DBC from confirmed candidates for an asset."""
    path = db_path or default_db_path()
    initialize(path)
    asset = get_asset_by_key(asset_key, db_path=path)

    candidates, skipped = _load_confirmed_candidates(
        asset_key,
        db_path=path,
        include_protocol_fields=include_protocol_fields,
    )
    warnings: list[GenerationWarning] = []

    by_frame: dict[tuple[bool, int], list[ResearchCandidateRecord]] = defaultdict(list)
    for candidate in candidates:
        by_frame[_frame_group_key(candidate)].append(candidate)

    messages: list[DbcMessage] = []
    signals_generated = 0
    used_message_names: set[str] = set()

    for frame_key in sorted(by_frame, key=lambda key: (key[0], key[1])):
        group = by_frame[frame_key]
        is_extended, can_id = frame_key
        representative = group[0]
        used_names: set[str] = set()
        occupied: list[tuple[int, int]] = []
        dbc_signals: list[DbcSignal] = []

        for candidate in sorted(
            group,
            key=lambda row: (row.start_bit, row.bit_length, row.signal_name or ""),
        ):
            bit_range = signal_bit_range(candidate.start_bit, candidate.bit_length)
            overlap = any(_bit_ranges_overlap(bit_range, existing) for existing in occupied)
            if overlap:
                skipped += 1
                warnings.append(
                    GenerationWarning(
                        category="signal_overlap",
                        message=(
                            f"Confirmed candidate {candidate.id} overlaps another signal "
                            f"in message 0x{can_id:X}"
                        ),
                        can_id=can_id,
                    )
                )
                continue

            signal_name = candidate.signal_name
            assert signal_name is not None
            if signal_name in used_names:
                skipped += 1
                warnings.append(
                    GenerationWarning(
                        category="duplicate_signal_name",
                        message=f"Duplicate signal name {signal_name!r} on 0x{can_id:X}",
                        can_id=can_id,
                    )
                )
                continue

            byte_order = 1 if candidate.byte_order == "intel" else 0
            signed = candidate.signedness == "signed"
            dbc_signals.append(
                DbcSignal(
                    name=signal_name,
                    start_bit=candidate.start_bit,
                    bit_length=candidate.bit_length,
                    byte_order=byte_order,
                    signed=signed,
                    factor=candidate.factor or 0.0,
                    offset=candidate.offset or 0.0,
                    minimum=candidate.minimum or 0.0,
                    maximum=candidate.maximum or 0.0,
                    unit=candidate.unit or "",
                    pgn=candidate.pgn or 0,
                    spn=0,
                    origin="research",
                    reference_backed=False,
                )
            )
            used_names.add(signal_name)
            occupied.append(bit_range)
            signals_generated += 1

        if not dbc_signals:
            continue

        message_name = _research_message_name(representative, used_names=used_message_names)
        used_message_names.add(message_name)

        dbc_frame_id = (
            encode_dbc_extended_id(can_id)
            if is_extended
            else can_id
        )
        messages.append(
            DbcMessage(
                name=message_name,
                can_id=can_id,
                dbc_frame_id=dbc_frame_id,
                dlc=DEFAULT_DLC,
                transmitter=DEFAULT_NODE,
                pgn=representative.pgn or 0,
                source_address=representative.source_address or 0,
                destination_address=representative.destination_address,
                origin="research",
                signals=tuple(
                    sorted(dbc_signals, key=lambda sig: (sig.start_bit, sig.bit_length, sig.name))
                ),
            )
        )

    session_ids = _session_ids_for_candidates(candidates)
    provenance = DbcProvenance(
        asset_key=asset.asset_key,
        asset_id=asset.id,
        session_id=session_ids[0] if len(session_ids) == 1 else "",
        dbc_type=DBC_TYPE_RESEARCH,
        reference_origins=(),
        generator_version=__version__,
        generated_at="",
        source_addresses=tuple(
            sorted({c.source_address for c in candidates if c.source_address is not None})
        ),
    )
    comments = _provenance_comments(
        asset_key=asset.asset_key,
        confirmed_count=len(candidates),
        session_ids=session_ids,
    )

    database = DbcDatabase(
        version="",
        nodes=(DEFAULT_NODE,),
        messages=tuple(sorted(messages, key=lambda msg: msg.dbc_frame_id)),
        provenance=provenance,
        comments=comments,
    )

    return ResearchDbcSummary(
        asset_key=asset.asset_key,
        asset_id=asset.id,
        dbc_type=DBC_TYPE_RESEARCH,
        confirmed_signal_count=len(candidates),
        messages_generated=len(messages),
        signals_generated=signals_generated,
        signals_skipped=skipped,
        warnings=tuple(warnings),
        database=database,
    )


def write_asset_research_dbc(
    asset_key: str,
    output: Path | None = None,
    *,
    db_path: Path | None = None,
    include_protocol_fields: bool = False,
) -> ResearchDbcSummary:
    """Generate and write <asset_key>_research.dbc."""
    summary = generate_asset_research_dbc(
        asset_key,
        db_path=db_path,
        include_protocol_fields=include_protocol_fields,
    )
    output_path = output or Path(default_dbc_filename(asset_key, dbc_type="research"))
    write_dbc(summary.database, output_path)
    return ResearchDbcSummary(
        asset_key=summary.asset_key,
        asset_id=summary.asset_id,
        dbc_type=summary.dbc_type,
        confirmed_signal_count=summary.confirmed_signal_count,
        messages_generated=summary.messages_generated,
        signals_generated=summary.signals_generated,
        signals_skipped=summary.signals_skipped,
        warnings=summary.warnings,
        database=summary.database,
        output_path=output_path,
    )


def preview_research_dbc_text(
    asset_key: str,
    *,
    preview_lines: int = 100,
    db_path: Path | None = None,
    include_protocol_fields: bool = False,
) -> tuple[ResearchDbcSummary, str]:
    summary = generate_asset_research_dbc(
        asset_key,
        db_path=db_path,
        include_protocol_fields=include_protocol_fields,
    )
    text = render_dbc(summary.database)
    lines = text.splitlines()
    if preview_lines < len(lines):
        truncated = "\n".join(lines[:preview_lines]) + "\n..."
        return summary, truncated
    return summary, text
